version: '2'
services:
  app:
    build: ./crosssense
    image: areth/crosssense:latest
    ports:
      - "3000"
    environment:
      - MONGODB_URI_DEV=mongodb://db/crosssense-dev
      - MONGODB_URI_TEST=mongodb://db/crosssense-test
    links:
      - db

  lserver:
    build: ./crosssense-lserver
    image: areth/crosssense-lserver:latest
    links:
      - db

  db:
    image: mongo
    expose:
      - "27017"